name: Build
run-name: ${{ startsWith(github.ref, 'refs/tags/v') && format('Release {0}', github.ref_name) || null }}

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          target: [ uiOvpn23, skeletonOvpn2, uiOvpn2 ]
    name: "Build :: ${{ matrix.target }}"
    runs-on: ubuntu-latest
    steps:
      - name: Use debug signing
        run: mkdir -p ~/.gradle && echo -e "icsopenvpnDebugSign=true\norg.gradle.jvmargs=-Xmx2048M" > ~/.gradle/gradle.properties

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Build the app
        run: ./gradlew assemble${{ matrix.target }}Release

      - name: Run Unit tests
        run: ./gradlew test${{ matrix.target }}ReleaseUnitTest

      - name: Archive apk artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{matrix.target}}-release-apk
          path: main/build/outputs/apk/**/*universal*.apk
