name: Build
run-name: ${{ startsWith(github.ref, 'refs/tags/v') && format('Release {0}', github.ref_name) || null }}

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          target: [ uiOvpn23 ] #, skeletonOvpn2, uiOvpn2 ]
    name: "Build :: ${{ matrix.target }}"
    runs-on: ubuntu-latest
    steps:
      - name: Use debug signing
        run: mkdir -p ~/.gradle && echo -e "icsopenvpnDebugSign=true\norg.gradle.jvmargs=-Xmx2048M" > ~/.gradle/gradle.properties

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Apply patches
        run: |
          sudo apt update -qq && sudo apt install -y quilt rename
          cd main/src/main/cpp/openvpn && QUILT_PATCHES=$GITHUB_WORKSPACE/patches quilt push -a

      - name: Build the app
        run: ./gradlew assemble${{ matrix.target }}Release

      - name: Run Unit tests
        run: ./gradlew test${{ matrix.target }}ReleaseUnitTest

      - name: Sign apk files
        uses: noriban/sign-android-release@v5
        id: sign_apk
        with:
          releaseDirectory: main/build/outputs/apk/${{ matrix.target }}/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename apk files
        run: |
          find . -type f -name '*-signed.apk' -exec mv {} . \;
          prename "s/^main-ui/ics-openvpn_${GITHUB_REF_NAME#v}/;s/-release.+(?=\.)//" *.apk

      - name: Upload release assets
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          prerelease: false
          draft: false
          body: |
            ### ics-openvpn ${{ github.ref_name }}
          files: ics-openvpn*.apk
